### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by guilhermevini** [chriszarate/docker-wordpress-vip#2]
This is a wordpress instalation with VIP plugins. 
I thought it was a wordpress vip quickstart instalation. 

=(

**Comment by chriszarate** [comment]
This is intended to be a Docker alternative for VIP Quickstart. I use it exclusively for WP VIP development. What features from VIP Quickstart is it missing? I'd like to bring it on par.

**Comment by chriszarate** [comment]
Added mu-plugins, wp-config.php, and changed to multisite install, all mirroring VIP QuickStart. Would be interested in your feedback.

**Comment by guilhermevini** [comment]
VIP QuickStart use puppet and another things like the folder structure.
But, your installation works fine. =)

**Comment by chriszarate** [comment]
Got it. I've tried to follow their approach as much as possible, but have deliberately left behind memcached and asset minification for speed.
