### ISSUE TITLE
Plugin directory volume instead of individual plugins.

### ISSUE THREAD

**Issue by garand** [chriszarate/docker-wordpress-vip#3]
Hey! Is it possible to mount something like

`plugins:/var/www/html/wp-content/plugins`

Rather than:

`plugins/jetpack:/var/www/html/wp-content/plugins/jetpack`
`plugins/something:/var/www/html/wp-content/plugins/something`
`plugins/another-plugin:/var/www/html/wp-content/plugins/another-plugin`

**Comment by chriszarate** [comment]
Absolutely, that's what is being done now in `docker-compose.yml`:

`lib-plugins:/var/www/html/wp-content/plugins`

To add additional plugins, edit `lib/Dockerfile`, following the pattern of other plugins, then rebuild and restart:

```
docker-compose build lib
docker-compose up -d
```

**Comment by garand** [comment]
Ah, gotcha! I'm a total Docker beginner. Really exciting stuff though, thanks for this project.
