### ISSUE TITLE
Should there be a /tmp/wordpress-tests-lib directory?

### ISSUE THREAD

**Issue by MikeiLL** [chriszarate/docker-wordpress-vip#5]
Hey Chris.

New to Phpunit and no Docker expert either. When I run `docker-compose exec wordpress tests`, it errors out because my bootstrap file is looking for `/tmp/wordpress-tests-lib/includes/functions.php`.

As per [Pippin's Plugins tutorial](https://pippinsplugins.com/unit-tests-wordpress-plugins-setting-up-testing-suite/), I used wp-cli: `wp scaffold plugin-tests` to create the file structure.

Being that `/tmp` has a wordpress directory, but no `wordpress-tests-lib`, I tried running:

```
docker-compose exec wordpress bash wp-content/plugins/my-plugin/bin/install-wp-tests.sh wordpress_test wordpress 'wordpress' localhost latest
```

Which errors out without svn installed. I don't imagine installing subversion on the container is the answer.

I'm sure I'm missing a step. Can you point me in the right direction.

Thank you very much for this package set, by the way. I've linked to it from the above tutorial comments as well as from an SO post.

**Comment by MikeiLL** [comment]
I have also tried updating the bootstrap file, changing the path to `/tmp//tmp/wordpress/latest/`, but of course there is no `includes/functions.php` file there. I also deleted the phpunit scaffold files and ran:
`docker-compose exec wordpress wp scaffold plugin-tests `
Which again created the scaffold, but again pointing to `/tmp/wordpress-tests-lib/includes/functions.php`

**Comment by chriszarate** [comment]
Sorry for the trouble. I should make the test setup compatible with WP-CLI scaffold.

Don't run the `install-wp-tests.sh` script; the container has essentially already run that script. The issue is that the file locations are different than what WP-CLI's scaffold is expecting. To fix this, edit the beginning of your `tests/bootstap.php` to:

```php
$_tests_dir = getenv( 'WP_TESTS_DIR' );
if ( ! $_tests_dir ) {
	$_tests_dir = '/tmp/wordpress/latest/tests/phpunit';
}

if ( empty( getenv( 'WP_ABSPATH' ) ) ) {
	putenv( 'WP_ABSPATH=/tmp/wordpress/latest/src/' );
}

// Give access to tests_add_filter() function.
/* rest of file below */ 
```

This will get tests up and running on your container. However, if you commit these changes, that will break tests on Travis. I'll try to make changes to the tests structure to match what WP-CLI expects.

But, now you can run tests from the host machine with something like:

`docker-compose exec wordpress sh -c 'cd /var/www/html/wp-content/plugins/my-plugin/; phpunit'`

Changing directories as above is important since you have relative paths in your `phpunit.xml`.

**Comment by chriszarate** [comment]
@MikeiLL I've updated the this repo and the [underlying image](https://github.com/chriszarate/docker-wordpress) to be compatible with tests scaffolded by WP-CLI. You can discard the edits I suggested above. You will need to pull in the latest changes from this repo and then run `docker-compose pull` to pull in the latest images. (These changes won't take affect until you recreate the containers via a `down`/`up` cycle.)

Alternatively, if you're just using this repo for non-VIP WordPress development, I've created a new repo that may more closely track your needs:

https://github.com/chriszarate/docker-compose-wordpress

It's a bit simpler and more oriented towards single-plugin development.

**Comment by MikeiLL** [comment]
Super-awesome, man! I'm not quite clear on what VIP Plugin development is. Am I reading correctly that Wordpress VIP is an enterprise-level WP hosting platform that starts at $5000 a month? And that you can submit plugins to run on this platform, which will be peer-reviewed as part of consideration for inclusion?

**Comment by chriszarate** [comment]
Yes, that's correct. If you don't need to develop for that platform, then the [docker-compose-wordpress](https://github.com/chriszarate/docker-compose-wordpress) repo is a simpler place to start.

**Comment by MikeiLL** [comment]
Not to bog you down, man. FYI, was getting session_header started errors on tests:
```
headers already sent (output started at /tmp/wordpress/latest/tests/phpunit/includes/bootstrap.php
```
Ran 
```
docker-compose exec wordpress phpunit --self-upgrade
```
Now getting:
```
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /tmp/wordpress/latest/tests/phpunit/includes/testcase.php on line 1
```
Am going to go ahead and migrate to https://github.com/chriszarate/docker-compose-wordpress anyway and if could be that the issue is with my plugin and not the container. Wanted to make a note of it anyway.
