### ISSUE TITLE
Missing Memcached

### ISSUE THREAD

**Issue by tomjn** [chriszarate/docker-wordpress-vip#6]
Object caching is missing from this container, so behaviour may not match the final production environment. The VIP Go MU plugins repo has a memcached dropin already so it just needs setting up in the containers

**Comment by chriszarate** [comment]
I initially set out to do this, but IIRC the drop-in from vip-quickstart insists on memcache, which doesn't have a PHP7-compatible extension ready to install inside Docker. We didn't need it for local dev so I moved on. I'll take a look at the vip-go-mu-plugins version.

**Comment by tomjn** [comment]
We don't use `memcache`, we used `memcached` which should be available, I have it running on my own sites, and VVV uses it with PHP 7. I also wouldn't refer too much to VIP Quickstart as it's no longer supported, especially if you're doing things with VIP Go ( VIP Go uses Varnish instead of Batcache )
